name: build image

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY_SERVER: quay.io
  REGISTRY_NAMESPACE: katonic
  USER: ${{secrets.USER}}
  PASSWORD: ${{secrets.PASSWORD}}
  REPOSITORY_NAME: app-store
  TAG: auto-insurance-claims-fraud-prediction

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login "${{ env.REGISTRY_SERVER }}" -u "${{ env.USER }}" -p "${{ env.PASSWORD }}"
    
    - name: Build the Docker image
      run: |
        docker build . --file "${{ env.BUILD_PATH }}"/Dockerfile --tag "${{ env.REGISTRY_SERVER }}"/"${{ env.REGISTRY_NAMESPACE }}"/"${{ env.REPOSITORY_NAME }}":"${{ env.TAG }}"
      
    - name: Docker Push
      run: docker push "${{ env.REGISTRY_SERVER }}"/"${{ env.REGISTRY_NAMESPACE }}"/"${{ env.REPOSITORY_NAME }}":"${{ env.TAG }}"